# 4-drone simulation preset for mega_overrack_indoor
# Usage: ./scripts/run_system.sh --params config_mega_overrack_indoor/sim/multi_4drones.yaml

run_ros2_system:
  ros__parameters:
    world_file: worlds/mega_overrack_indoor.world
    agent_cmd_default: MicroXRCEAgent udp4 -p 8888 -v 6
    drones_yaml: |
      - name: drone_north_west
        namespace: px4_1
        model: iris_opt_flow
        spawn: {x: -6.5, y: 1.0, z: 1.2, yaw: 0.0}
        mavlink_udp_port: 14540
        px4_namespace: "/px4_1"
        log_dir: data/logs/mega_drone1
        mission_runner:
          mission_file: config_mega_overrack_indoor/mission_drone1_north_west.yaml
          sim.disable_link_after_s: 20.0

      - name: drone_north_east
        namespace: px4_2
        model: iris_opt_flow
        spawn: {x: 6.5, y: 1.0, z: 1.2, yaw: 0.0}
        mavlink_udp_port: 14541
        px4_namespace: "/px4_2"
        log_dir: data/logs/mega_drone2
        mission_runner:
          mission_file: config_mega_overrack_indoor/mission_drone2_north_east.yaml
          sim.disable_link_after_s: -1.0

      - name: drone_south_west
        namespace: px4_3
        model: iris_opt_flow
        spawn: {x: -6.5, y: -1.0, z: 1.2, yaw: 0.0}
        mavlink_udp_port: 14542
        px4_namespace: "/px4_3"
        log_dir: data/logs/mega_drone3
        mission_runner:
          mission_file: config_mega_overrack_indoor/mission_drone3_south_west.yaml
          sim.disable_link_after_s: -1.0

      - name: drone_south_east
        namespace: px4_4
        model: iris_opt_flow
        spawn: {x: 6.5, y: -1.0, z: 1.2, yaw: 0.0}
        mavlink_udp_port: 14543
        px4_namespace: "/px4_4"
        log_dir: data/logs/mega_drone4
        mission_runner:
          mission_file: config_mega_overrack_indoor/mission_drone4_south_east.yaml
          sim.disable_link_after_s: -1.0

mission_runner:
  ros__parameters:
    world_bounds.x: [-24.0, 24.0]
    world_bounds.y: [-10.0, 10.0]
    world_bounds.z: [-3.0, -0.1]
    debug_frames: true
    return_home_safe_z: 2.0
    sim.disable_link_after_s: -1.0

inspection_node:
  ros__parameters:
    image_topic: overrack/iris/front_camera/image_raw
    low_light_threshold: 90.0
    suspect_variance: 12.0
    publish_period_s: 0.5

torch_controller:
  ros__parameters:
    command_topic: overrack/torch_enable
    startup_on: false
    min_on_seconds: 10.0
